->
  try
    throw new Error()
  catch e
    x = 4

  { x: x
  }
